# Generated by Django 5.1.9 on 2026-06-19 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('super_admin', 'مدیر کل سیستم'), ('institution_admin', 'مدیر مؤسسه، دانشگاه یا مدرسه'), ('exam_manager', 'مدیر آموزش یا مسئول امتحانات'), ('teacher', 'استاد یا طراح سؤال'), ('teaching_assistant', 'کمک\u200cاستاد یا دستیار آموزشی'), ('student', 'دانشجو یا داوطلب')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('access_level', models.PositiveSmallIntegerField(default=1)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('duties', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نقش سیستم',
                'verbose_name_plural': 'نقش\u200cهای سیستم',
                'ordering': ['-access_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تاریخچه فعالیت',
                'verbose_name_plural': 'تاریخچه فعالیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_name', models.CharField(blank=True, max_length=160)),
                ('was_successful', models.BooleanField(default=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سابقه ورود',
                'verbose_name_plural': 'سوابق ورود',
                'ordering': ['-logged_in_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('father_name', models.CharField(blank=True, max_length=120)),
                ('national_code', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('organizational_email', models.EmailField(blank=True, max_length=254)),
                ('residential_address', models.TextField(blank=True)),
                ('profile_image', models.FileField(blank=True, upload_to='profiles/')),
                ('personnel_number', models.CharField(blank=True, max_length=40)),
                ('student_number', models.CharField(blank=True, max_length=40)),
                ('applicant_code', models.CharField(blank=True, max_length=40)),
                ('institution_name', models.CharField(blank=True, max_length=180)),
                ('organizational_position', models.CharField(blank=True, max_length=120)),
                ('faculty_or_unit', models.CharField(blank=True, max_length=160)),
                ('department', models.CharField(blank=True, max_length=160)),
                ('field_of_study', models.CharField(blank=True, max_length=160)),
                ('specialization', models.CharField(blank=True, max_length=160)),
                ('academic_rank_or_job_title', models.CharField(blank=True, max_length=160)),
                ('education_level', models.CharField(blank=True, max_length=80)),
                ('entrance_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, max_length=40)),
                ('class_or_group', models.CharField(blank=True, max_length=120)),
                ('education_status', models.CharField(blank=True, choices=[('active', 'مشغول به تحصیل'), ('graduated', 'فارغ\u200cالتحصیل'), ('suspended', 'تعلیق'), ('withdrawn', 'انصراف')], max_length=30)),
                ('account_status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('blocked', 'مسدود')], default='active', max_length=20)),
                ('access_scope', models.TextField(blank=True)),
                ('responsibility_scope', models.TextField(blank=True)),
                ('cooperation_type', models.CharField(blank=True, max_length=120)),
                ('cooperation_started_at', models.DateField(blank=True, null=True)),
                ('cooperation_ended_at', models.DateField(blank=True, null=True)),
                ('account_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('teachable_courses', models.JSONField(blank=True, default=list)),
                ('selected_courses', models.JSONField(blank=True, default=list)),
                ('related_courses', models.JSONField(blank=True, default=list)),
                ('devices', models.JSONField(blank=True, default=list)),
                ('login_records', models.JSONField(blank=True, default=list)),
                ('assigned_exams', models.JSONField(blank=True, default=list)),
                ('exam_status', models.JSONField(blank=True, default=dict)),
                ('submitted_files', models.JSONField(blank=True, default=list)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('objections', models.JSONField(blank=True, default=list)),
                ('position_documents', models.FileField(blank=True, upload_to='profile-documents/')),
                ('resume_or_academic_document', models.FileField(blank=True, upload_to='profile-documents/')),
                ('digital_signature', models.FileField(blank=True, upload_to='signatures/')),
                ('digital_stamp', models.FileField(blank=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.systemrole')),
                ('supervisor_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
                'ordering': ['full_name'],
            },
        ),
    ]
