# Generated by Django 5.1.9 on 2026-06-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_proctor_and_support_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinstitution',
            name='registration_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='systemadminprofile',
            name='admin_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
