# Generated by Django 5.1.9 on 2026-06-20 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_academicinstitution_registration_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='emergency_resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='emergency_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='emergency_stop_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='emergency_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='emergency_stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_stopped_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('scheduled', 'زمان\u200cبندی\u200cشده'), ('active', 'در حال برگزاری'), ('paused', 'متوقف اضطراری'), ('finished', 'پایان\u200cیافته'), ('cancelled', 'لغوشده')], default='draft', max_length=20),
        ),
    ]
