# Generated by Django 5.1.9 on 2026-06-20 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exam_emergency_resolution_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_approval', 'در انتظار تأیید'), ('scheduled', 'زمان\u200cبندی\u200cشده'), ('active', 'در حال برگزاری'), ('paused', 'متوقف اضطراری'), ('finished', 'پایان\u200cیافته'), ('cancelled', 'لغوشده')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.academicinstitution')),
            ],
            options={
                'verbose_name': 'نیم\u200cسال تحصیلی',
                'verbose_name_plural': 'نیم\u200cسال\u200cهای تحصیلی',
                'ordering': ['-year', 'title'],
                'unique_together': {('institution', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ExamViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_file', models.FileField(blank=True, upload_to='violations/evidence/')),
                ('proctor_note', models.TextField(blank=True)),
                ('teacher_note', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('rejected', 'رد گزارش'), ('warning', 'اخطار'), ('score_deduction', 'کسر نمره'), ('invalidate_exam', 'ابطال آزمون'), ('refer_committee', 'ارجاع به کمیته انضباطی')], default='pending', max_length=30)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_violations', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_reports', to='core.exam')),
                ('proctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_reports', to='core.examproctorprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_reports', to='core.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violation_reports', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'گزارش تخلف آزمون',
                'verbose_name_plural': 'گزارش\u200cهای تخلف آزمون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.academicinstitution')),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to='core.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core.teacherprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core.academicterm')),
            ],
            options={
                'verbose_name': 'کلاس درس',
                'verbose_name_plural': 'کلاس\u200cهای درس',
                'ordering': ['title'],
                'unique_together': {('institution', 'code')},
            },
        ),
    ]
