# Generated by Django 5.1.9 on 2026-06-20 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_exam_status_academicterm_examviolationreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('returned', 'بازگشت برای اصلاح')], default='pending', max_length=20)),
                ('question_count', models.PositiveIntegerField(blank=True, null=True)),
                ('participants_count', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='core.exam')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_approval_requests', to='core.teacherprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exam_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تأیید آزمون',
                'verbose_name_plural': 'تأیید آزمون\u200cها',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamExecutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('incomplete_count', models.PositiveIntegerField(default=0)),
                ('internet_disconnects', models.PositiveIntegerField(default=0)),
                ('violations_count', models.PositiveIntegerField(default=0)),
                ('final_note', models.TextField(blank=True)),
                ('sent_to_institution_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_report', to='core.exam')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_exam_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش برگزاری آزمون',
                'verbose_name_plural': 'گزارش\u200cهای برگزاری آزمون',
            },
        ),
        migrations.CreateModel(
            name='ExamRescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_starts_at', models.DateTimeField()),
                ('old_ends_at', models.DateTimeField()),
                ('new_starts_at', models.DateTimeField()),
                ('new_ends_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'ردشده')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='core.exam')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_reschedule_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exam_reschedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست تغییر زمان آزمون',
                'verbose_name_plural': 'درخواست\u200cهای تغییر زمان آزمون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamStartAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_entered', models.PositiveIntegerField(default=0)),
                ('absent_students', models.PositiveIntegerField(default=0)),
                ('proctor_ready', models.BooleanField(default=False)),
                ('teacher_ready', models.BooleanField(default=False)),
                ('authorized', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_exam_starts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_authorization', to='core.exam')),
            ],
            options={
                'verbose_name': 'مجوز شروع آزمون',
                'verbose_name_plural': 'مجوزهای شروع آزمون',
            },
        ),
        migrations.CreateModel(
            name='ExamProctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'تخصیص داده\u200cشده'), ('accepted', 'پذیرفته\u200cشده'), ('rejected', 'ردشده')], default='assigned', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exam_proctors', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to='core.exam')),
                ('proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.examproctorprofile')),
            ],
            options={
                'verbose_name': 'تخصیص ناظر آزمون',
                'verbose_name_plural': 'تخصیص ناظران آزمون',
                'ordering': ['-assigned_at'],
                'unique_together': {('exam', 'proctor')},
            },
        ),
    ]
