# Generated by Django 5.1.9 on 2026-06-20 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_examapproval_examexecutionreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_backtracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_result_after_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExamResultPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_score', models.BooleanField(default=True)),
                ('show_correct_answers', models.BooleanField(default=False)),
                ('show_rank', models.BooleanField(default=False)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('highest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lowest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_publication', to='core.exam')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'انتشار نتیجه آزمون',
                'verbose_name_plural': 'انتشار نتایج آزمون',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'چهارگزینه\u200cای'), ('true_false', 'صحیح و غلط'), ('fill_blank', 'جای\u200cخالی'), ('short_answer', 'پاسخ کوتاه'), ('descriptive', 'تشریحی'), ('matching', 'تطبیقی')], max_length=30)),
                ('text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=20)),
                ('chapter', models.CharField(blank=True, max_length=120)),
                ('topic', models.CharField(blank=True, max_length=160)),
                ('suggested_score', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'بانک سؤال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DescriptiveAnswerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('finalized', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptive_reviews', to='core.exam')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptive_reviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptive_reviews', to='core.studentprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptive_reviews', to='core.question')),
            ],
            options={
                'verbose_name': 'تصحیح پاسخ تشریحی',
                'verbose_name_plural': 'تصحیح پاسخ\u200cهای تشریحی',
                'ordering': ['finalized', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objection_text', models.TextField()),
                ('original_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('revised_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('decision', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'تأیید اعتراض'), ('rejected', 'رد اعتراض')], default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_objections', to='core.exam')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_objections', to='core.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_objections', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objection_records', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'اعتراض دانشجو',
                'verbose_name_plural': 'اعتراض\u200cهای دانشجویان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='core.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_links', to='core.question')),
            ],
            options={
                'verbose_name': 'سؤال آزمون',
                'verbose_name_plural': 'سؤالات آزمون',
                'ordering': ['order', 'id'],
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
