# Generated by Django 5.1.9 on 2026-06-21 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_exam_allow_backtracking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantExamDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده برای استاد'), ('approved', 'تأیید و منتشر شده'), ('rejected', 'رد شده')], default='submitted', max_length=20)),
                ('teacher_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_exam_drafts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_draft', to='core.exam')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assistant_exam_drafts', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_exam_drafts', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'پیش\u200cنویس آزمون دستیار',
                'verbose_name_plural': 'پیش\u200cنویس\u200cهای آزمون دستیاران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید استاد'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('needs_revision', 'نیازمند اصلاح')], default='pending', max_length=30)),
                ('teacher_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_question_submissions', to=settings.AUTH_USER_MODEL)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_submission', to='core.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assistant_questions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_question_submissions', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'ارسال سؤال توسط دستیار',
                'verbose_name_plural': 'ارسال سؤال\u200cهای دستیاران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantQuestionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_text', models.TextField(blank=True)),
                ('suggested_correct_answer', models.TextField(blank=True)),
                ('suggested_topic', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('teacher_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_question_suggestions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_suggestions', to='core.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_question_suggestions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_question_suggestions', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'پیشنهاد اصلاح سؤال',
                'verbose_name_plural': 'پیشنهادهای اصلاح سؤال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('assigned', 'تخصیص داده شده'), ('submitted', 'ارسال شده برای تأیید استاد'), ('approved', 'تأیید شده'), ('returned', 'برگشت برای اصلاح')], default='assigned', max_length=20)),
                ('teacher_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_review_assignments', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_assignment', to='core.descriptiveanswerreview')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assistant_reviews', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_review_assignments', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'تخصیص تصحیح به دستیار',
                'verbose_name_plural': 'تخصیص\u200cهای تصحیح دستیاران',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('answered', 'پاسخ داده شده'), ('referred', 'ارجاع شده به استاد')], default='new', max_length=20)),
                ('needs_teacher_decision', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_educational_questions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_questions', to='core.course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_questions', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_questions', to='core.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_questions', to='core.teacherprofile')),
            ],
            options={
                'verbose_name': 'پرسش آموزشی',
                'verbose_name_plural': 'پرسش\u200cهای آموزشی',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
