# Generated by Django 5.1.9 on 2026-06-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_assistantexamdraft_assistantquestionsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentobjection',
            name='evidence_file',
            field=models.FileField(blank=True, upload_to='objections/evidence/'),
        ),
        migrations.AddField(
            model_name='studentobjection',
            name='objection_type',
            field=models.CharField(choices=[('score', 'اعتراض به نمره'), ('question', 'اعتراض به سؤال'), ('answer_key', 'اعتراض به کلید پاسخ'), ('technical', 'مشکل فنی')], default='score', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('waiting_proctor', 'در انتظار تصمیم ناظر'), ('in_progress', 'در حال آزمون'), ('submitted', 'ارسال شده'), ('auto_submitted', 'ارسال خودکار'), ('blocked', 'مسدود')], default='not_started', max_length=30)),
                ('identity_confirmed', models.BooleanField(default=False)),
                ('rules_accepted', models.BooleanField(default=False)),
                ('identity_code', models.CharField(blank=True, max_length=60)),
                ('identity_image', models.FileField(blank=True, upload_to='attempts/identity/')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_code', models.CharField(blank=True, max_length=40)),
                ('proctor_note', models.TextField(blank=True)),
                ('can_continue_after_disconnect', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'شرکت دانشجو در آزمون',
                'verbose_name_plural': 'شرکت دانشجویان در آزمون',
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentExamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('entered_early', 'مراجعه زودتر از زمان'), ('entry_expired', 'مراجعه پس از پایان زمان'), ('identity_failed', 'احراز هویت ناموفق'), ('started', 'شروع آزمون'), ('answer_saved', 'ذخیره پاسخ'), ('disconnected', 'قطع اتصال'), ('reconnected', 'اتصال مجدد'), ('file_rejected', 'رد فایل پاسخ'), ('submitted', 'ارسال نهایی'), ('auto_submitted', 'ارسال خودکار')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.studentexamattempt')),
            ],
            options={
                'verbose_name': 'رویداد آزمون دانشجو',
                'verbose_name_plural': 'رویدادهای آزمون دانشجو',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPracticeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_ok', models.BooleanField(default=False)),
                ('internet_ok', models.BooleanField(default=False)),
                ('camera_ok', models.BooleanField(default=False)),
                ('microphone_ok', models.BooleanField(default=False)),
                ('sample_score', models.PositiveSmallIntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_checks', to='core.studentprofile')),
            ],
            options={
                'verbose_name': 'بررسی آزمون آزمایشی',
                'verbose_name_plural': 'بررسی\u200cهای آزمون آزمایشی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('uploaded_file', models.FileField(blank=True, upload_to='attempts/answers/')),
                ('marked_for_review', models.BooleanField(default=False)),
                ('autosaved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.studentexamattempt')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='core.examquestion')),
            ],
            options={
                'verbose_name': 'پاسخ دانشجو',
                'verbose_name_plural': 'پاسخ\u200cهای دانشجویان',
                'ordering': ['exam_question__order', 'id'],
                'unique_together': {('attempt', 'exam_question')},
            },
        ),
    ]
