# Generated by Django 5.1.9 on 2026-08-21 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_academic_unit_path(apps, schema_editor):
    """پر کردن path برای واحدهای سازمانی موجود، از ریشه به سمت برگ‌ها.

    ردیف‌های قبلی این فیلد را خالی دارند (تازه اضافه شده)؛ AcademicUnit.save()
    فقط هنگام ذخیره‌ی دوباره‌ی هر رکورد آن را پر می‌کند، نه برای رکوردهای
    از قبل موجود. اینجا با پیمایش سطح‌به‌سطح (فرزندان بعد از والدین) مقدار
    صحیح را برای همه محاسبه می‌کنیم.
    """
    AcademicUnit = apps.get_model('core', 'AcademicUnit')
    remaining = list(AcademicUnit.objects.all().only('id', 'parent_id', 'path'))
    computed = {}
    changed = True
    while remaining and changed:
        changed = False
        still_remaining = []
        for unit in remaining:
            if unit.parent_id is None:
                computed[unit.id] = f'{unit.id}/'
                changed = True
            elif unit.parent_id in computed:
                computed[unit.id] = f'{computed[unit.parent_id]}{unit.id}/'
                changed = True
            else:
                still_remaining.append(unit)
        remaining = still_remaining
    for unit in remaining:
        # حلقه در داده‌ی قدیمی (نباید رخ دهد، AcademicUnit.clean() از این
        # جلوگیری می‌کند) — برای این رکوردهای باقی‌مانده مسیر تک‌سطحی می‌گذاریم
        # تا داده‌ای گم نشود، اما این وضعیت باید دستی بررسی شود.
        computed[unit.id] = f'{unit.id}/'
    for unit_id, path in computed.items():
        AcademicUnit.objects.filter(pk=unit_id).update(path=path)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_question_builder_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=40)),
                ('position_title', models.CharField(blank=True, max_length=120)),
                ('can_manage_teachers', models.BooleanField(default=True)),
                ('can_manage_students', models.BooleanField(default=True)),
                ('can_schedule_exams', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('appointment_started_at', models.DateField(blank=True, null=True)),
                ('appointment_ended_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پروفایل مدیر آموزشی',
                'verbose_name_plural': 'پروفایل\u200cهای مدیران آموزشی',
            },
        ),
        migrations.AddField(
            model_name='academicunit',
            name='path',
            field=models.CharField(blank=True, editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'چهارگزینه\u200cای'), ('multi_select', 'چندپاسخی'), ('true_false', 'صحیح و غلط'), ('fill_blank', 'جای\u200cخالی'), ('short_answer', 'پاسخ کوتاه'), ('descriptive', 'تشریحی'), ('matching', 'تطبیقی'), ('ordering', 'مرتب\u200cسازی')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='academicunit',
            index=models.Index(fields=['path'], name='core_academ_path_1d3cb1_idx'),
        ),
        migrations.AddField(
            model_name='exammanagerprofile',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_managers', to='core.academicinstitution'),
        ),
        migrations.AddField(
            model_name='exammanagerprofile',
            name='managed_units',
            field=models.ManyToManyField(blank=True, help_text='واحدهای سازمانی (و همه\u200cی زیرشاخه\u200cهای هرکدام) که این مدیر آموزشی به آن\u200cها دسترسی دارد.', related_name='exam_managers', to='core.academicunit'),
        ),
        migrations.AddField(
            model_name='exammanagerprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_manager_profile', to='core.userprofile'),
        ),
        migrations.RunPython(backfill_academic_unit_path, noop_reverse),
    ]
