# Generated by Django 5.1.9 on 2026-08-21 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_phase3_exam_manager_profile_and_unit_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='آیا این همان نقشی است که در UserProfile.role هم ثبت شده.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.userprofile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.systemrole')),
            ],
            options={
                'verbose_name': 'تخصیص نقش کاربر',
                'verbose_name_plural': 'تخصیص\u200cهای نقش کاربران',
                'ordering': ['-is_primary', '-role__access_level'],
                'unique_together': {('profile', 'role')},
            },
        ),
    ]
