# Generated by Django 5.1.9 on 2026-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_phase3b_user_role_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicinstitution',
            name='legacy_erd_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='legacy_erd_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='academicunit',
            name='legacy_erd_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='legacy_erd_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='legacy_erd_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='exam',
            name='legacy_erd_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='legacy_erd_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
