from django.urls import path
from .views import (
    assistant_educational_question_answer,
    assistant_educational_questions,
    assistant_exam_draft_create,
    assistant_panel,
    assistant_question_suggestions,
    assistant_questions,
    assistant_review_detail,
    assistant_reviews,
    SecureLoginView,
    dashboard,
    exam_manager_active_exams,
    exam_manager_approval_review,
    exam_manager_approvals,
    exam_manager_calendar,
    exam_manager_dashboard,
    exam_manager_proctors,
    exam_manager_reports,
    exam_manager_reschedule,
    exam_manager_start_control,
    home,
    institution_admin_dashboard,
    institution_assign_exam_manager,
    institution_exam_detail,
    institution_exams,
    institution_settings,
    institution_structure,
    institution_users,
    institution_violation_decision,
    institution_violations,
    login_2fa,
    logout_view,
    super_admin_active_exams,
    super_admin_dashboard,
    super_admin_emergency_stop,
    super_admin_institution_create,
    super_admin_reports,
    super_admin_resolve_emergency,
    super_admin_roles,
    super_admin_user_detail,
    super_admin_users,
    student_educational_questions,
    student_attempt,
    student_attempt_event,
    student_attempt_receipt,
    student_attempt_submit,
    student_exam_detail,
    student_exam_entry,
    student_exam_schedule,
    student_exam_start,
    student_objections,
    student_practice_exam,
    student_result_detail,
    student_results,
    teacher_assistant_exam_draft_review,
    teacher_assistant_question_review,
    teacher_assistant_requests,
    teacher_assistant_review_decision,
    teacher_assistant_suggestion_review,
    teacher_assign_review,
    teacher_educational_question_answer,
    teacher_exam_create,
    teacher_exam_preview,
    teacher_exams,
    teacher_extend_exam,
    teacher_monitoring,
    teacher_objection_detail,
    teacher_objections,
    teacher_panel,
    teacher_publish_result,
    teacher_questions,
    teacher_review_detail,
    teacher_reviews,
    teacher_results,
)

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('logout/', logout_view, name='logout'),
    path('login/', SecureLoginView.as_view(), name='login'),
    path('login/verify/', login_2fa, name='login_2fa'),
    path('super-admin/', super_admin_dashboard, name='super_admin_dashboard'),
    path('super-admin/institutions/create/', super_admin_institution_create, name='super_admin_institution_create'),
    path('super-admin/users/', super_admin_users, name='super_admin_users'),
    path('super-admin/users/<int:profile_id>/', super_admin_user_detail, name='super_admin_user_detail'),
    path('super-admin/roles/', super_admin_roles, name='super_admin_roles'),
    path('super-admin/reports/', super_admin_reports, name='super_admin_reports'),
    path('super-admin/exams/active/', super_admin_active_exams, name='super_admin_active_exams'),
    path('super-admin/exams/<int:exam_id>/emergency-stop/', super_admin_emergency_stop, name='super_admin_emergency_stop'),
    path('super-admin/exams/<int:exam_id>/emergency/<str:resolution>/', super_admin_resolve_emergency, name='super_admin_resolve_emergency'),
    path('institution-admin/', institution_admin_dashboard, name='institution_admin_dashboard'),
    path('institution-admin/settings/', institution_settings, name='institution_settings'),
    path('institution-admin/users/', institution_users, name='institution_users'),
    path('institution-admin/structure/', institution_structure, name='institution_structure'),
    path('institution-admin/exam-manager/', institution_assign_exam_manager, name='institution_assign_exam_manager'),
    path('institution-admin/exams/', institution_exams, name='institution_exams'),
    path('institution-admin/exams/<int:exam_id>/', institution_exam_detail, name='institution_exam_detail'),
    path('institution-admin/violations/', institution_violations, name='institution_violations'),
    path('institution-admin/violations/<int:report_id>/', institution_violation_decision, name='institution_violation_decision'),
    path('exam-manager/', exam_manager_dashboard, name='exam_manager_dashboard'),
    path('exam-manager/calendar/', exam_manager_calendar, name='exam_manager_calendar'),
    path('exam-manager/approvals/', exam_manager_approvals, name='exam_manager_approvals'),
    path('exam-manager/approvals/<int:approval_id>/', exam_manager_approval_review, name='exam_manager_approval_review'),
    path('exam-manager/proctors/', exam_manager_proctors, name='exam_manager_proctors'),
    path('exam-manager/active-exams/', exam_manager_active_exams, name='exam_manager_active_exams'),
    path('exam-manager/active-exams/<int:exam_id>/start-control/', exam_manager_start_control, name='exam_manager_start_control'),
    path('exam-manager/reschedule/', exam_manager_reschedule, name='exam_manager_reschedule'),
    path('exam-manager/reports/', exam_manager_reports, name='exam_manager_reports'),
    path('teacher/', teacher_panel, name='teacher_panel'),
    path('teacher/assistant-requests/', teacher_assistant_requests, name='teacher_assistant_requests'),
    path('teacher/assistant-requests/questions/<int:submission_id>/', teacher_assistant_question_review, name='teacher_assistant_question_review'),
    path('teacher/assistant-requests/suggestions/<int:suggestion_id>/', teacher_assistant_suggestion_review, name='teacher_assistant_suggestion_review'),
    path('teacher/assistant-requests/exam-drafts/<int:draft_id>/', teacher_assistant_exam_draft_review, name='teacher_assistant_exam_draft_review'),
    path('teacher/assistant-requests/reviews/<int:assignment_id>/', teacher_assistant_review_decision, name='teacher_assistant_review_decision'),
    path('teacher/assistant-requests/educational-questions/<int:question_id>/', teacher_educational_question_answer, name='teacher_educational_question_answer'),
    path('teacher/questions/', teacher_questions, name='teacher_questions'),
    path('teacher/exams/', teacher_exams, name='teacher_exams'),
    path('teacher/exams/create/', teacher_exam_create, name='teacher_exam_create'),
    path('teacher/exams/<int:exam_id>/preview/', teacher_exam_preview, name='teacher_exam_preview'),
    path('teacher/monitoring/', teacher_monitoring, name='teacher_monitoring'),
    path('teacher/monitoring/<int:exam_id>/extend/', teacher_extend_exam, name='teacher_extend_exam'),
    path('teacher/reviews/', teacher_reviews, name='teacher_reviews'),
    path('teacher/reviews/<int:review_id>/assign-assistant/', teacher_assign_review, name='teacher_assign_review'),
    path('teacher/reviews/<int:review_id>/', teacher_review_detail, name='teacher_review_detail'),
    path('teacher/results/', teacher_results, name='teacher_results'),
    path('teacher/results/<int:exam_id>/publish/', teacher_publish_result, name='teacher_publish_result'),
    path('teacher/objections/', teacher_objections, name='teacher_objections'),
    path('teacher/objections/<int:objection_id>/', teacher_objection_detail, name='teacher_objection_detail'),
    path('assistant/', assistant_panel, name='assistant_panel'),
    path('assistant/questions/', assistant_questions, name='assistant_questions'),
    path('assistant/exam-drafts/', assistant_exam_draft_create, name='assistant_exam_drafts'),
    path('assistant/question-suggestions/', assistant_question_suggestions, name='assistant_question_suggestions'),
    path('assistant/reviews/', assistant_reviews, name='assistant_reviews'),
    path('assistant/reviews/<int:assignment_id>/', assistant_review_detail, name='assistant_review_detail'),
    path('assistant/educational-questions/', assistant_educational_questions, name='assistant_educational_questions'),
    path('assistant/educational-questions/<int:question_id>/', assistant_educational_question_answer, name='assistant_educational_question_answer'),
    path('student/educational-questions/', student_educational_questions, name='student_educational_questions'),
    path('student/exams/', student_exam_schedule, name='student_exam_schedule'),
    path('student/exams/<int:exam_id>/', student_exam_detail, name='student_exam_detail'),
    path('student/exams/<int:exam_id>/entry/', student_exam_entry, name='student_exam_entry'),
    path('student/exams/<int:exam_id>/start/', student_exam_start, name='student_exam_start'),
    path('student/practice/', student_practice_exam, name='student_practice_exam'),
    path('student/attempts/<int:attempt_id>/', student_attempt, name='student_attempt'),
    path('student/attempts/<int:attempt_id>/event/', student_attempt_event, name='student_attempt_event'),
    path('student/attempts/<int:attempt_id>/submit/', student_attempt_submit, name='student_attempt_submit'),
    path('student/attempts/<int:attempt_id>/receipt/', student_attempt_receipt, name='student_attempt_receipt'),
    path('student/results/', student_results, name='student_results'),
    path('student/results/<int:attempt_id>/', student_result_detail, name='student_result_detail'),
    path('student/objections/', student_objections, name='student_objections'),
]
