from django.urls import path
from .views import (
    assistant_educational_question_answer,
    assistant_educational_questions,
    assistant_exam_draft_create,
    assistant_panel,
    assistant_question_suggestions,
    assistant_questions,
    assistant_review_detail,
    assistant_reviews,
    SecureLoginView,
    dashboard,
    exam_manager_active_exams,
    exam_manager_approval_review,
    exam_manager_approvals,
    exam_manager_calendar,
    exam_manager_calendar_create,
    exam_manager_course_create,
    exam_manager_course_detail,
    exam_manager_courses,
    exam_manager_dashboard,
    exam_manager_exam_create,
    exam_manager_exam_detail,
    exam_manager_exam_import,
    exam_manager_exam_questions,
    exam_manager_exam_results,
    exam_manager_exams,
    exam_manager_group_create,
    exam_manager_group_detail,
    exam_manager_group_import,
    exam_manager_group_students_add,
    exam_manager_group_teacher_assign,
    exam_manager_groups,
    exam_manager_student_create,
    exam_manager_teacher_create,
    exam_manager_teacher_profile,
    exam_manager_user_import,
    exam_manager_users,
    exam_manager_proctors,
    exam_manager_reports,
    exam_manager_reschedule,
    exam_manager_start_control,
    home,
    institution_admin_dashboard,
    institution_assign_exam_manager,
    institution_exam_detail,
    institution_exams,
    institution_settings,
    institution_structure,
    institution_users,
    institution_violation_decision,
    institution_violations,
    login_2fa,
    logout_view,
    profile_view,
    register,
    super_admin_active_exams,
    super_admin_academic_managers,
    super_admin_academic_terms,
    super_admin_calendar,
    super_admin_course_form,
    super_admin_courses,
    super_admin_dashboard,
    super_admin_emergency_stop,
    super_admin_exam_create,
    super_admin_exam_detail,
    super_admin_exam_edit,
    super_admin_exam_bulk_import,
    super_admin_exams,
    super_admin_group_create,
    super_admin_group_edit,
    super_admin_groups,
    super_admin_institution_create,
    super_admin_org_units,
    super_admin_reports,
    super_admin_resolve_emergency,
    super_admin_roles,
    super_admin_settings,
    super_admin_students,
    super_admin_student_create,
    super_admin_student_bulk_import,
    super_admin_student_profile_edit,
    super_admin_teachers,
    super_admin_teacher_create,
    super_admin_teacher_bulk_import,
    super_admin_teacher_courses,
    super_admin_teacher_profile_edit,
    super_admin_manager_access,
    super_admin_manager_create,
    super_admin_manager_bulk_import,
    super_admin_manager_profile_edit,
    super_admin_user_profile,
    super_admin_user_detail,
    super_admin_users,
    super_admin_toggle_account_status,
    super_admin_delete_account,
    student_educational_questions,
    student_attempt,
    student_attempt_event,
    student_attempt_receipt,
    student_attempt_submit,
    student_exam_detail,
    student_exam_entry,
    student_exam_schedule,
    student_exam_start,
    student_objections,
    student_practice_exam,
    student_result_detail,
    student_results,
    teacher_assistant_exam_draft_review,
    teacher_assistant_question_review,
    teacher_assistant_requests,
    teacher_assistant_review_decision,
    teacher_assistant_suggestion_review,
    teacher_assign_review,
    teacher_announcements,
    teacher_calendar,
    teacher_course_detail,
    teacher_courses,
    teacher_educational_question_answer,
    teacher_exam_create,
    teacher_exam_preview,
    teacher_exams,
    teacher_group_activity,
    teacher_group_students,
    teacher_extend_exam,
    teacher_monitoring,
    teacher_objection_detail,
    teacher_objections,
    teacher_panel,
    teacher_profile_page,
    teacher_publish_result,
    teacher_question_bulk_import,
    teacher_question_create,
    teacher_question_edit,
    teacher_question_type,
    teacher_questions,
    teacher_review_detail,
    teacher_reviews,
    teacher_results,
    teacher_security,
    teacher_settings,
    teacher_student_profile,
)

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('profile/', profile_view, name='profile'),
    path('logout/', logout_view, name='logout'),
    path('login/', SecureLoginView.as_view(), name='login'),
    path('register/', register, name='register'),
    path('login/verify/', login_2fa, name='login_2fa'),
    path('super-admin/', super_admin_dashboard, name='super_admin_dashboard'),
    path('super-admin/courses/', super_admin_courses, name='super_admin_courses'),
    path('super-admin/courses/new/', super_admin_course_form, name='super_admin_course_new'),
    path('super-admin/courses/<str:course_id>/edit/', super_admin_course_form, name='super_admin_course_edit'),
    path('super-admin/teachers/', super_admin_teachers, name='super_admin_teachers'),
    path('super-admin/teachers/new/', super_admin_teacher_create, name='super_admin_teacher_create'),
    path('super-admin/teachers/bulk/', super_admin_teacher_bulk_import, name='super_admin_teacher_bulk_import'),
    path('super-admin/students/', super_admin_students, name='super_admin_students'),
    path('super-admin/students/new/', super_admin_student_create, name='super_admin_student_create'),
    path('super-admin/students/bulk/', super_admin_student_bulk_import, name='super_admin_student_bulk_import'),
    path('super-admin/managers/new/', super_admin_manager_create, name='super_admin_manager_create'),
    path('super-admin/managers/bulk/', super_admin_manager_bulk_import, name='super_admin_manager_bulk_import'),
    path('super-admin/groups/', super_admin_groups, name='super_admin_groups'),
    path('super-admin/groups/new/', super_admin_group_create, name='super_admin_group_create'),
    path('super-admin/groups/<str:group_id>/edit/', super_admin_group_edit, name='super_admin_group_edit'),
    path('super-admin/exams/', super_admin_exams, name='super_admin_exams'),
    path('super-admin/exams/new/', super_admin_exam_create, name='super_admin_exam_create'),
    path('super-admin/exams/bulk/', super_admin_exam_bulk_import, name='super_admin_exam_bulk_import'),
    path('super-admin/exams/<str:exam_id>/edit/', super_admin_exam_edit, name='super_admin_exam_edit'),
    path('super-admin/exams/<str:exam_id>/', super_admin_exam_detail, name='super_admin_exam_detail'),
    path('super-admin/calendar/', super_admin_calendar, name='super_admin_calendar'),
    path('super-admin/org-units/', super_admin_org_units, name='super_admin_org_units'),
    path('super-admin/academic-managers/', super_admin_academic_managers, name='super_admin_academic_managers'),
    path('super-admin/academic-terms/', super_admin_academic_terms, name='super_admin_academic_terms'),
    path('super-admin/settings/', super_admin_settings, name='super_admin_settings'),
    path('super-admin/institutions/create/', super_admin_institution_create, name='super_admin_institution_create'),
    path('super-admin/users/', super_admin_users, name='super_admin_users'),
    path('super-admin/users/manager/<str:user_id>/access/', super_admin_manager_access, name='super_admin_manager_access'),
    path('super-admin/users/manager/<str:user_id>/profile/edit/', super_admin_manager_profile_edit, name='super_admin_manager_profile_edit'),
    path('super-admin/users/student/<str:user_id>/profile/edit/', super_admin_student_profile_edit, name='super_admin_student_profile_edit'),
    path('super-admin/users/teacher/<str:user_id>/courses/', super_admin_teacher_courses, name='super_admin_teacher_courses'),
    path('super-admin/users/teacher/<str:user_id>/profile/edit/', super_admin_teacher_profile_edit, name='super_admin_teacher_profile_edit'),
    path('super-admin/users/<str:kind>/<str:user_id>/profile/', super_admin_user_profile, name='super_admin_user_profile'),
    path('super-admin/users/<str:kind>/<str:user_id>/toggle-status/', super_admin_toggle_account_status, name='super_admin_toggle_account_status'),
    path('super-admin/users/<str:kind>/<str:user_id>/delete/', super_admin_delete_account, name='super_admin_delete_account'),
    path('super-admin/users/<int:profile_id>/', super_admin_user_detail, name='super_admin_user_detail'),
    path('super-admin/roles/', super_admin_roles, name='super_admin_roles'),
    path('super-admin/reports/', super_admin_reports, name='super_admin_reports'),
    path('super-admin/exams/active/', super_admin_active_exams, name='super_admin_active_exams'),
    path('super-admin/exams/<str:exam_id>/emergency-stop/', super_admin_emergency_stop, name='super_admin_emergency_stop'),
    path('super-admin/exams/<str:exam_id>/emergency/<str:resolution>/', super_admin_resolve_emergency, name='super_admin_resolve_emergency'),
    path('institution-admin/', institution_admin_dashboard, name='institution_admin_dashboard'),
    path('institution-admin/settings/', institution_settings, name='institution_settings'),
    path('institution-admin/users/', institution_users, name='institution_users'),
    path('institution-admin/structure/', institution_structure, name='institution_structure'),
    path('institution-admin/exam-manager/', institution_assign_exam_manager, name='institution_assign_exam_manager'),
    path('institution-admin/exams/', institution_exams, name='institution_exams'),
    path('institution-admin/exams/<int:exam_id>/', institution_exam_detail, name='institution_exam_detail'),
    path('institution-admin/violations/', institution_violations, name='institution_violations'),
    path('institution-admin/violations/<int:report_id>/', institution_violation_decision, name='institution_violation_decision'),
    path('exam-manager/', exam_manager_dashboard, name='exam_manager_dashboard'),
    path('exam-manager/courses/', exam_manager_courses, name='exam_manager_courses'),
    path('exam-manager/courses/new/', exam_manager_course_create, name='exam_manager_course_create'),
    path('exam-manager/courses/<str:course_id>/', exam_manager_course_detail, name='exam_manager_course_detail'),
    path('exam-manager/groups/', exam_manager_groups, name='exam_manager_groups'),
    path('exam-manager/groups/new/', exam_manager_group_create, name='exam_manager_group_create'),
    path('exam-manager/groups/import/', exam_manager_group_import, name='exam_manager_group_import'),
    path('exam-manager/groups/teacher-assign/', exam_manager_group_teacher_assign, name='exam_manager_group_teacher_assign'),
    path('exam-manager/groups/<str:group_id>/', exam_manager_group_detail, name='exam_manager_group_detail'),
    path('exam-manager/groups/<str:group_id>/students/add/', exam_manager_group_students_add, name='exam_manager_group_students_add'),
    path('exam-manager/users/', exam_manager_users, name='exam_manager_users'),
    path('exam-manager/users/students/new/', exam_manager_student_create, name='exam_manager_student_create'),
    path('exam-manager/users/teachers/new/', exam_manager_teacher_create, name='exam_manager_teacher_create'),
    path('exam-manager/users/teachers/<str:teacher_id>/', exam_manager_teacher_profile, name='exam_manager_teacher_profile'),
    path('exam-manager/users/import/', exam_manager_user_import, name='exam_manager_user_import'),
    path('exam-manager/calendar/', exam_manager_calendar, name='exam_manager_calendar'),
    path('exam-manager/calendar/new/', exam_manager_calendar_create, name='exam_manager_calendar_create'),
    path('exam-manager/exams/', exam_manager_exams, name='exam_manager_exams'),
    path('exam-manager/exams/new/', exam_manager_exam_create, name='exam_manager_exam_create'),
    path('exam-manager/exams/import/', exam_manager_exam_import, name='exam_manager_exam_import'),
    path('exam-manager/exams/<str:exam_id>/', exam_manager_exam_detail, name='exam_manager_exam_detail'),
    path('exam-manager/exams/<str:exam_id>/questions/', exam_manager_exam_questions, name='exam_manager_exam_questions'),
    path('exam-manager/exams/<str:exam_id>/results/', exam_manager_exam_results, name='exam_manager_exam_results'),
    path('exam-manager/approvals/', exam_manager_approvals, name='exam_manager_approvals'),
    path('exam-manager/approvals/<int:approval_id>/', exam_manager_approval_review, name='exam_manager_approval_review'),
    path('exam-manager/proctors/', exam_manager_proctors, name='exam_manager_proctors'),
    path('exam-manager/active-exams/', exam_manager_active_exams, name='exam_manager_active_exams'),
    path('exam-manager/active-exams/<int:exam_id>/start-control/', exam_manager_start_control, name='exam_manager_start_control'),
    path('exam-manager/reschedule/', exam_manager_reschedule, name='exam_manager_reschedule'),
    path('exam-manager/reports/', exam_manager_reports, name='exam_manager_reports'),
    path('teacher/', teacher_panel, name='teacher_panel'),
    path('teacher/announcements/', teacher_announcements, name='teacher_announcements'),
    path('teacher/courses/', teacher_courses, name='teacher_courses'),
    path('teacher/courses/<str:group_id>/', teacher_course_detail, name='teacher_course_detail'),
    path('teacher/courses/<str:group_id>/students/', teacher_group_students, name='teacher_group_students'),
    path('teacher/courses/<str:group_id>/activity/', teacher_group_activity, name='teacher_group_activity'),
    path('teacher/students/<str:student_id>/', teacher_student_profile, name='teacher_student_profile'),
    path('teacher/calendar/', teacher_calendar, name='teacher_calendar'),
    path('teacher/profile/', teacher_profile_page, name='teacher_profile_page'),
    path('teacher/settings/', teacher_settings, name='teacher_settings'),
    path('teacher/security/', teacher_security, name='teacher_security'),
    path('teacher/assistant-requests/', teacher_assistant_requests, name='teacher_assistant_requests'),
    path('teacher/assistant-requests/questions/<int:submission_id>/', teacher_assistant_question_review, name='teacher_assistant_question_review'),
    path('teacher/assistant-requests/suggestions/<int:suggestion_id>/', teacher_assistant_suggestion_review, name='teacher_assistant_suggestion_review'),
    path('teacher/assistant-requests/exam-drafts/<int:draft_id>/', teacher_assistant_exam_draft_review, name='teacher_assistant_exam_draft_review'),
    path('teacher/assistant-requests/reviews/<int:assignment_id>/', teacher_assistant_review_decision, name='teacher_assistant_review_decision'),
    path('teacher/assistant-requests/educational-questions/<int:question_id>/', teacher_educational_question_answer, name='teacher_educational_question_answer'),
    path('teacher/questions/', teacher_questions, name='teacher_questions'),
    path('teacher/questions/type/', teacher_question_type, name='teacher_question_type'),
    path('teacher/questions/new/', teacher_question_create, name='teacher_question_create'),
    path('teacher/questions/import/', teacher_question_bulk_import, name='teacher_question_bulk_import'),
    path('teacher/questions/<str:question_id>/edit/', teacher_question_edit, name='teacher_question_edit'),
    path('teacher/exams/', teacher_exams, name='teacher_exams'),
    path('teacher/exams/create/', teacher_exam_create, name='teacher_exam_create'),
    path('teacher/exams/<str:exam_id>/preview/', teacher_exam_preview, name='teacher_exam_preview'),
    path('teacher/monitoring/', teacher_monitoring, name='teacher_monitoring'),
    path('teacher/monitoring/<str:exam_id>/extend/', teacher_extend_exam, name='teacher_extend_exam'),
    path('teacher/reviews/', teacher_reviews, name='teacher_reviews'),
    path('teacher/reviews/<int:review_id>/assign-assistant/', teacher_assign_review, name='teacher_assign_review'),
    path('teacher/reviews/<int:review_id>/', teacher_review_detail, name='teacher_review_detail'),
    path('teacher/results/', teacher_results, name='teacher_results'),
    path('teacher/results/<str:exam_id>/publish/', teacher_publish_result, name='teacher_publish_result'),
    path('teacher/objections/', teacher_objections, name='teacher_objections'),
    path('teacher/objections/<str:objection_id>/', teacher_objection_detail, name='teacher_objection_detail'),
    path('assistant/', assistant_panel, name='assistant_panel'),
    path('assistant/questions/', assistant_questions, name='assistant_questions'),
    path('assistant/exam-drafts/', assistant_exam_draft_create, name='assistant_exam_drafts'),
    path('assistant/question-suggestions/', assistant_question_suggestions, name='assistant_question_suggestions'),
    path('assistant/reviews/', assistant_reviews, name='assistant_reviews'),
    path('assistant/reviews/<int:assignment_id>/', assistant_review_detail, name='assistant_review_detail'),
    path('assistant/educational-questions/', assistant_educational_questions, name='assistant_educational_questions'),
    path('assistant/educational-questions/<int:question_id>/', assistant_educational_question_answer, name='assistant_educational_question_answer'),
    path('student/educational-questions/', student_educational_questions, name='student_educational_questions'),
    path('student/exams/', student_exam_schedule, name='student_exam_schedule'),
    path('student/exams/<str:exam_id>/', student_exam_detail, name='student_exam_detail'),
    path('student/exams/<str:exam_id>/entry/', student_exam_entry, name='student_exam_entry'),
    path('student/exams/<str:exam_id>/start/', student_exam_start, name='student_exam_start'),
    path('student/practice/', student_practice_exam, name='student_practice_exam'),
    path('student/attempts/<str:attempt_id>/', student_attempt, name='student_attempt'),
    path('student/attempts/<str:attempt_id>/event/', student_attempt_event, name='student_attempt_event'),
    path('student/attempts/<str:attempt_id>/submit/', student_attempt_submit, name='student_attempt_submit'),
    path('student/attempts/<str:attempt_id>/receipt/', student_attempt_receipt, name='student_attempt_receipt'),
    path('student/results/', student_results, name='student_results'),
    path('student/results/<str:attempt_id>/', student_result_detail, name='student_result_detail'),
    path('student/objections/', student_objections, name='student_objections'),
]
